### ISSUE TITLE
Phosphor Issue [Latest commit]

### ISSUE THREAD

**Issue by TerdyTheTerd** [Gegy/tic-tacs#24] opened 2020-12-16 03:57 UTC
Unsure if the latest commit was ready to be tested, but I did anyways and the server was crashing with
`Caused by: java.lang.ClassNotFoundException: me.jellysquid.mods.phosphor.common.chunk.light.ServerLightingProviderAccess`
from tictacs.

If phosphor compat isn't finished yet ignore this or close it.

**Comment by Gegy** [comment] 2020-12-16 06:28
Thanks for the report! I believe this is caused by using the release version of Phosphor, where the compatibility was made only with the development branch in mind. Will be looking into resolving this, but it is possible to avoid by updating from the latest commit on the Phosphor dev branch :)

**Closed as completed** 2020-12-16 07:16 UTC
Labels: bug
