### ISSUE TITLE
Server crash upon player joining

### ISSUE THREAD

**Issue by DrexHD** [Gegy/tic-tacs#6] opened 2020-09-01 20:29 UTC
The server crashed when I rejoined (first join worked).

Server log:
```
net.minecraft.class_148: Exception ticking world
	at Not Enough Crashes deobfuscated stack trace.(1.16.2+build.1) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickWorlds(MinecraftServer:872) ~[intermediary-server.jar:?]
	at net.minecraft.server.dedicated.MinecraftDedicatedServer.tickWorlds(MinecraftDedicatedServer:303) ~[?:?]
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer:808) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer:667) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer:254) ~[intermediary-server.jar:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_265]

java.lang.IllegalStateException: Chunk not there when requested: UNLOADED
    at Not Enough Crashes deobfuscated stack trace.(1.16.2+build.1)
    at net.minecraft.server.world.ServerChunkManager.method_16173(ServerChunkManager:145)
    at com.mojang.datafixers.util.Either$Right.map(Either.java:99)
    at net.minecraft.server.world.ServerChunkManager.getChunk(ServerChunkManager:143)
    at net.minecraft.world.World.getChunk(World:209)
    at net.minecraft.world.World.getBlockState(World:1226)
    at net.minecraft.block.entity.BlockEntity.getCachedState(BlockEntity:124)
    at net.minecraft.block.entity.BlockEntity.populateCrashReport(BlockEntity:165)
    at net.minecraft.world.World.tickBlockEntities(World:519)
    at net.minecraft.server.world.ServerWorld.tick(ServerWorld:424)
    at net.minecraft.server.MinecraftServer.tickWorlds(MinecraftServer:868)
    at net.minecraft.server.dedicated.MinecraftDedicatedServer.tickWorlds(MinecraftDedicatedServer:303)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer:808)
    at net.minecraft.server.MinecraftServer.runServer(MinecraftServer:667)
    at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer:254)
    at java.lang.Thread.run(Thread.java:748)
```

**Comment by Gegy** [comment] 2020-09-05 20:20
This should have been resolved in https://github.com/gegy1000/tic-tacs/commit/50bf07420dce83dce2ff50dc43c8164a7861a76c. Let me know if the issue is still occurring 🙂

**Closed as completed by Gegy** 2020-09-05 20:20 UTC
Labels: bug
