### ISSUE TITLE
Some chunks have weird behaviour

### ISSUE THREAD

**Issue by DrexHD** [Gegy/tic-tacs#8] opened 2020-09-01 20:56 UTC
A couple of chunks have weird behaviour:
- Items can't be picked up
- Blocks can (sometimes) not be broken
- Entitys don't tick (for some reason I can hit them once though)
- Block updates don't get sent to the client (interacting updates them tough)
- Randomticks don't work
(I hope this gives an idea of what might be happening / causing this)
While rejoining the server doesn't fix the chunks for the player, a server restart does.

**Comment by Gegy** [comment] 2020-09-04 16:34
I've possibly been able to resolve this in https://github.com/gegy1000/tic-tacs/commit/394a9604b41ce8d74a32d63a970c9333bba33634, but I'm not super confident due to it being pretty inconsistent to reproduce. Leaving this issue open for now, though

**Comment by Gegy** [comment] 2020-09-05 20:16
This should have been properly fixed in https://github.com/gegy1000/tic-tacs/commit/50bf07420dce83dce2ff50dc43c8164a7861a76c

**Closed as completed by Gegy** 2020-09-05 20:16 UTC
Labels: bug

**Comment by DrexHD** [comment] 2020-09-05 22:06
As mentioned 394a9604b41ce8d74a32d63a970c9333bba33634 didn't fix this issue, after testing for about 10-20 minutes with 50bf07420dce83dce2ff50dc43c8164a7861a76c I wasn't able to reproduce it anymore.
