### ISSUE TITLE
Player is kicked

### ISSUE THREAD

**Issue by DrexHD** [Gegy/tic-tacs#7] opened 2020-09-01 20:37 UTC
While quickly flying through the world, I sometimes get kicked ("Internal server error").
Server log:

```
[22:35:40] [Server thread/WARN]: Failed to handle packet for /xx.xxx.xxx.xx:xxxxx
net.minecraft.class_148: Ticking player
        at Not Enough Crashes deobfuscated stack trace.(1.16.2+build.1) ~[?:?]
        at net.minecraft.server.network.ServerPlayerEntity.playerTick(ServerPlayerEntity:492) ~[?:?]
        at net.minecraft.server.network.ServerPlayNetworkHandler.tick(ServerPlayNetworkHandler:207) ~[?:?]
        at net.minecraft.network.ClientConnection.tick(ClientConnection:234) ~[?:?]
        at net.minecraft.server.ServerNetworkIo.tick(ServerNetworkIo:173) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickWorlds(MinecraftServer:879) ~[intermediary-server.jar:?]
        at net.minecraft.server.dedicated.MinecraftDedicatedServer.tickWorlds(MinecraftDedicatedServer:303) ~[?:?]
        at net.minecraft.server.MinecraftServer.tick(MinecraftServer:808) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer:667) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer:254) ~[intermediary-server.jar:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_265]
Caused by: java.lang.IllegalStateException: No chunk holder after ticket has been added
        at Not Enough Crashes deobfuscated stack trace.(1.16.2+build.1) ~[?:?]
        at net.minecraft.server.world.ServerChunkManager.getChunkFuture(ServerChunkManager:227) ~[?:?]
        at net.minecraft.server.world.ServerChunkManager.getChunk(ServerChunkManager:140) ~[?:?]
        at net.minecraft.world.World.getChunk(World:209) ~[?:?]
        at net.minecraft.world.World.getBlockState(World:1226) ~[?:?]
        at net.minecraft.entity.Entity.move(Entity:606) ~[?:?]
        at net.minecraft.entity.LivingEntity.travel(LivingEntity:2076) ~[?:?]
        at net.minecraft.entity.player.PlayerEntity.travel(PlayerEntity:1568) ~[?:?]
        at net.minecraft.entity.LivingEntity.tickMovement(LivingEntity:2547) ~[?:?]
        at net.minecraft.entity.player.PlayerEntity.tickMovement(PlayerEntity:566) ~[?:?]
        at net.minecraft.entity.LivingEntity.tick(LivingEntity:2254) ~[?:?]
        at net.minecraft.entity.player.PlayerEntity.tick(PlayerEntity:274) ~[?:?]
        at net.minecraft.server.network.ServerPlayerEntity.playerTick(ServerPlayerEntity:428) ~[?:?]
        ... 9 more
```

**Comment by Gegy** [comment] 2020-09-05 20:20
This should have been resolved in https://github.com/gegy1000/tic-tacs/commit/50bf07420dce83dce2ff50dc43c8164a7861a76c. Let me know if the issue is still occurring 🙂

**Closed as completed by Gegy** 2020-09-05 20:20 UTC
Labels: bug
